using System.Text;

namespace Lilypad; 

public class Function : Resource {
    readonly List<object> _commands = new();

    public Function(string name, Datapack datapack) : base(name, datapack) { }
    
    internal Function Add(object command) {
        _commands.Add(command);
        return this;
    }
    
    internal T AddAndReturn<T>(T command) {
        _commands.Add(command!);
        return command;
    }

    public Function SetTick() => AddToMinecraftTag("tick");
    public Function SetLoad() => AddToMinecraftTag("load");

    Function AddToMinecraftTag(string name) {
        var tag = Datapack.FunctionTags.GetOrCreate(name, Namespaces.Minecraft);
        tag.Add(this);
        return this;
    }

    public override string ToString() {
        var builder = new StringBuilder();
            
        builder.AppendLine("# Generated by Lilypad");
        builder.AppendLine();
            
        foreach (var command in _commands) {
            var str = command.ToString();
            if (string.IsNullOrWhiteSpace(str)) continue;
            
            var lines = str.Split('\n');
            foreach (var line in lines) {
                builder.AppendLine(line);
            }
        }
            
        return builder.ToString();
    }
}