using Lilypad.Extensions;

namespace Lilypad; 

public static class ParticleFunctionExtensions {
    public static Function Particle(
        this Function function, 
        EnumReference<Particle> particle,
        Vector3? position = null
    ) {
        return function.Add($"particle {particle} {position.ToStringOrEmpty()}");
    }

    public static Function Particle(
        this Function function,
        EnumReference<Particle> particle,
        Vector3 position,
        Vector3 delta,
        float speed,
        int count,
        bool force = false,
        Argument<Selector>? viewers = null
    ) {
        var mode = force ? "force" : "normal";
        return function.Add($"particle {particle} {position} {delta} {speed} {count} {mode} {viewers.ToStringOrEmpty()}");
    }
}

public enum Particle {
    AmbientEntityEffect,
    AngryVillager,
    Ash,
    Block,
    Blockdust,
    BlockMarker,
    Bubble,
    BubbleColumnUp,
    BubblePop,
    CampfireCosySmoke,
    CampfireSignalSmoke,
    CherryLeaves,
    Cloud,
    Composter,
    CrimsonSpore,
    Crit,
    CurrentDown,
    DamageIndicator,
    Dolphin,
    DragonBreath,
    DrippingDripstoneLava,
    DrippingDripstoneWater,
    DrippingHoney,
    DrippingLava,
    DrippingObsidianTear,
    DrippingWater,
    Dust,
    DustColorTransition,
    Effect,
    ElderGuardian,
    ElectricSpark,
    Enchant,
    EnchantedHit,
    EndRod,
    EntityEffect,
    Explosion,
    ExplosionEmitter,
    FallingDripstoneLava,
    FallingDripstoneWater,
    FallingDust,
    FallingHoney,
    FallingLava,
    FallingNectar,
    FallingObsidianTear,
    FallingSporeBlossom,
    FallingWater,
    Firework,
    Fishing,
    Flame,
    Flash,
    Glow,
    GlowSquidInk,
    HappyVillager,
    Heart,
    InstantEffect,
    Item,
    ItemSlime,
    ItemSnowball,
    LandingHoney,
    LandingLava,
    LandingObsidianTear,
    LargeSmoke,
    Lava,
    Mycelium,
    Nautilus,
    Note,
    Poof,
    Portal,
    Rain,
    Scrape,
    SculkCharge,
    SculkChargePop,
    SculkSoul,
    Shriek,
    Smoke,
    Sneeze,
    Snowflake,
    SonicBoom,
    Soul,
    SoulFireFlame,
    Spit,
    SporeBlossomAir,
    Splash,
    SquidInk,
    SweepAttack,
    TotemOfUndying,
    Underwater,
    Vibration,
    WarpedSpore,
    WaxOff,
    WaxOn,
    WhiteAsh,
    Witch,
}