using Lilypad;
using Lilypad.Scoreboards;
using Lilypad.Text;

const string outputPath = @"C:\Users\bobbo\AppData\Roaming\PrismLauncher\instances\Default 1.20.1\.minecraft\saves\Testing\datapacks\lilypad-example";

var datapack = new Datapack {
    Description = "An example datapack generated by Lilypad"
};

var kills = new Objective(
    datapack,
    displayName: "<red><b>Kills",
    displaySlot: DisplaySlot.Sidebar
);

datapack.Functions.Create(f => {
    f.Tellraw(Selector.All, "<url https://www.youtube.com/watch?v=dQw4w9WgXcQ><gold><u>This is <b>definitely</b> not a rick roll.</u></url></color> I promise!");
    f.Execute().As("@a").Run(g => {
        g.Say("Hello, world!");
        g.Scoreboard(kills).Set("@s", 0);
    });
}).SetLoad();

datapack.Transpile(new TranspilationOptions(outputPath));